language: python
python:
  - "3.7"

install:
  - pip install pipenv
  - pipenv install --dev

script:
  # - pylint **/*.py
  - python -m pytest tests/*
  - cd docs && make html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: docs/_build/html/