name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
            python-version: '3.7'
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
          pip install -e .
      - name: Build docs
        run: |
          cd docs && make html
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages # The branch the action should deploy to.
            FOLDER: ./docs/html
            CLEAN: true # Automatically remove deleted files from the deploy branch
